/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp org.freedesktop.portal.Screenshot.xml -a screenshot_adaptor
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef SCREENSHOT_ADAPTOR_H
#define SCREENSHOT_ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
//class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.freedesktop.portal.Screenshot
 */
class ScreenshotAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.portal.Screenshot")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.portal.Screenshot\">\n"
"    <method name=\"Screenshot\">\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In1\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"parent_window\"/>\n"
"      <arg direction=\"in\" type=\"a{sv}\" name=\"options\"/>\n"
"      <arg direction=\"out\" type=\"o\" name=\"handle\"/>\n"
"    </method>\n"
"    <method name=\"PickColor\">\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In1\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"parent_window\"/>\n"
"      <arg direction=\"in\" type=\"a{sv}\" name=\"options\"/>\n"
"      <arg direction=\"out\" type=\"o\" name=\"handle\"/>\n"
"    </method>\n"
"    <property access=\"read\" type=\"u\" name=\"version\"/>\n"
"  </interface>\n"
        "")
public:
    ScreenshotAdaptor(QObject *parent);
    virtual ~ScreenshotAdaptor();

public: // PROPERTIES
    Q_PROPERTY(uint version READ version)
    uint version() const;

public Q_SLOTS: // METHODS
    QDBusObjectPath PickColor(const QString &parent_window, const QVariantMap &options);
    QDBusObjectPath Screenshot(const QString &parent_window, const QVariantMap &options);
Q_SIGNALS: // SIGNALS
};

#endif
